### ISSUE TITLE
如何与默认symbols.yaml同时使用

### ISSUE THREAD

**Issue by YuruiHong** [wklchris/Rime-latex-symbols#1]
根据配置说明，需要更改`punctuator/import_preset`，而我的方案中已经在这里引用了symbols，替换为latexmath则symbols失效，应该如何同时使用两者？

**Comment by YuruiHong** [comment]
目前好像只能手动合并这两个文件，感觉不算很好的解决方法

**Comment by wklchris** [comment]
该问题已通过 [48d63cc](https://github.com/wklchris/Rime-latex-symbols/commit/48d63cca64533c49c4889b0c2e5b0fdd42f3e5a4) 修复。

请参考 ReadMe 说明，用 `latexmath_compatible.yaml` 文件代替 `latexmath.yaml` 对 RIME 进行配置。在本次更新后新增的`latexmath_compatible.yaml` 文件通过引入默认的字符文件 `symbols.yaml` 来实现字符集合并。
